/*
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence
 * whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class Solution {

  public static void main(String[] args) {
    int odd1 = 1;
    int odd2 = 1;
    int even = 0;
    int sum = 0;

    while (even < 4000000) {
      sum += even;
      odd1 = odd2 + even;
      odd2 = odd1 + even;
      even = odd1 + odd2;
    }

    System.out.println(sum);
  }
}
